### ISSUE TITLE
VS doesn't like defines for inlines in source

### ISSUE THREAD

**Issue by gamemachine** [nxrighthere/NanoSockets#2]
Minor thing more of an FYI, but VS is really annoying here it expects the defines to be in the header, so it will constantly not recognize the ones declared in the source file.  It compiles fine it just greys out all the inlines until you focus the source then go back to the header.  Unfocus the header and the whole cycle repeats.

**Comment by nxrighthere** [comment]
Does it helps if you declare prototypes like [this](https://www.diffchecker.com/3LqRwaPm)?

**Comment by gamemachine** [comment]
No.  NANOSOCKETS_IMPLEMENTATION just isn't picked up as defined.  Not a big deal since it stays defined as long as you are in the file and then randomly other times.  Is a bit curious though is there even a valid case where it would end up not being defined at compile time?

**Comment by nxrighthere** [comment]
Ah, now I understand what are you talking about. I've encountered this once in VS Code and just disabled the fading out of unused code since this feature is quite annoying when you work with source files selectively rather than with the entire project.

So, since the library is an amalgamated single-header file, the `NANOSOCKETS_IMPLEMENTATION` can be used in several ways depending on requirements:
1. Compilation of the library as is: as long as `nanosockets.c` is included the implementation will be used directly from the header.
2. External linkage: including just the header without `nanosockets.c` only for prototypes without using the implementation.
